[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
plugins = { path = "../plugins" }
bevy_editor_pls = "0.6.0"

[lints]
workspace = true
